fix: add missing README information and clean up types
coder/modules pull request #273
Opened 2024-07-19 20:23 UTC by Parkreiner

Little bit of cleanup to make the repo easier to maintain.

## Changes made
- Updated the main contributing guide to include release steps
- Cleaned up TypeScript implementation
   - Turned strict mode on
   - Removed all `any` types
   - Updated all runtime code to account for type changes

## Notes
- Going to look into adding images or even a gif for the release steps; will look into this on Monday

2024-07-19 20:52 UTC, stirby commented
@matifali @Parkreiner can we cut a release as soon as this is merged?

2024-07-19 21:23 UTC, Parkreiner commented
> @matifali @Parkreiner can we cut a release as soon as this is merged?

Atif and I just cut a release this afternoon. Were there any major changes after that? I would think this PR is just infrastructure stuff that won't affect end-users

2024-07-19 21:38 UTC, bcpeinhardt approved these changes
This is super useful on boarding info 😎

2024-07-20 03:47 UTC, matifali commented on README.md
> +[Module Registry](https://registry.coder.com) | [Coder Docs](https://coder.com/docs) | [Why Coder](https://coder.com/why) | [Coder Enterprise](https://coder.com/docs/v2/latest/enterprise)
Registry also hosts templates source code at https://registry.coder.com/templates

2024-07-20 03:47 UTC, matifali commented on CONTRIBUTING.md
> +1. Publishing new versions to Coder's [Terraform Registry](https://registry.terraform.io/providers/coder/coder/latest)
We do not publish anything to terraform registry.

2024-07-20 03:49 UTC, matifali approved these changes
Looking great for now. It may change once we implement independent versioning for each module. 
#157

2024-07-24 07:31 UTC, matifali requested changes
We do not publish modules to terraform registry. i.e registry.terraform.io

2024-07-31 06:23 UTC, matifali approved these changes
Thank you. :)

2024-08-03 16:51 UTC, merged