chore: add subdomain option to terraform module
coder/modules pull request #288
Opened 2024-08-29 17:32 UTC by Emyrk

2024-08-29 18:01 UTC, stirby requested changes
Breaks in my testing

2024-08-29 18:01 UTC, stirby commented on vscode-web/main.tf
> +  subdomain    = var.subdomain
Setting subdomain to false breaks the app. I think you'll have to chang the URL format when it's set.

2024-10-15 21:05 UTC, matifali commented
@Emyrk Do you plan to come back to this? A similar approach is used in #316 and #320.

2024-10-16 15:22 UTC, Emyrk commented
@matifali I think this has be done for it to work
https://github.com/coder/coder/issues/14483

I see the Juypter accomplishing this by setting the url to the full path, but I thought I tried that and it did not work for this.

2024-10-16 15:28 UTC, matifali commented
@Emyrk A Community member successfully ran Jupyter on a subpath by setting the full URL. See #313

2024-10-17 16:55 UTC, Emyrk commented
> @Emyrk A Community member successfully ran Jupyter on a subpath by setting the full URL. See #313

I do see that. I think it depends on how urls are constructed within the app. I _am pretty sure_ I tried this with VSCode and it did not. Using the exact same technique. 

If someone has more time to try it, please do.

2024-10-21 08:45 UTC, matifali commented
@code-asher @Emyrk I tested with both `subdomain=true|false` and it works. 
Also, I have noticed that skipping the `coder_agent`'s name auto updates the URL with the correct `agent_name`, so it is not necessary.

We can drop `agent_name` from all modules that support `subdomain=false`.

2024-10-21 08:45 UTC, matifali approved these changes

2024-10-21 08:46 UTC, matifali commented on vscode-web/main.tf
> +    SERVER_BASE_PATH : format("/@%s/%s.%s/apps/vscode-web/",
I have noticed that skipping the `coder_agent`'s name auto updates the URL with the correct `agent_name`, so it is unnecessary.

2024-10-21 08:46 UTC, merged