feat: add dotfiles module
coder/modules pull request #33
Opened 2023-09-24 05:29 UTC by bpmct

closes #5

2023-09-24 11:26 UTC, matifali commented
Are these ready to merge?

2023-09-24 17:39 UTC, bpmct commented
Yeah, I suppose. Just need to test

2023-09-25 09:07 UTC, matifali approved these changes
LGTM. You can merge after testing

2023-09-25 09:08 UTC, matifali requested changes

2023-09-25 09:08 UTC, matifali commented on dotfiles/README.md
> +icon: ../.icons/personalize.svg
Also, This icon is missing. Please add it.

2023-09-25 22:57 UTC, matifali commented
@bpmct can you get this in? It only needs a logo

2023-09-25 22:58 UTC, matifali approved these changes

2023-09-25 23:31 UTC, merged